
- name: instalando apache no debian
  package:
   name: apache2
  when: ansible_os_family == "Debian"

- name: instalando apache no cent_os
  package:
   name: httpd
  when: ansible_os_family == "RedHat"

- name: dando start no apache no cent_os #cent_os nao starta automatico o apache, por isso precisa fazer esse passo
  service:
   name: httpd
   state: started
  when: ansible_os_family == "RedHat"

