- name: instalando puppet server na maquina devops
  package:
   name: puppetserver
   update_cache: yes #antes de instalar atualizar o repositorio (sรณ precisa pra Debian, Cent_os jah faz automatico) 
  when:
   - ansible_hostname == "devops"

- name: instalando o puppetagent
  package:
   name: puppet-agent
   state: present
   update_cache: yes

- name: dando start no puppet-agent quando for cent_os
  service:
   name: puppet
   state: started
  when: ansible_os_family == "RedHat"
