
wordpress_dexter:
 image: wordpress #imagem do wordpress
 links:
  - mysql_dexter:mysql #container do wordpress espera por esse link
 ports:
  - 8081:80

mysql_dexter:
 image: mariadb
 environment: 
  MYSQL_ROOT_PASSWORD: dexter

