- name: instalando apache para debian
  package:
   name:
    - apache2
  when: ansible_os_family == "Debian" #variavel que  busca no setup/factory (checklist da maquina) da maquina

- name: instalando apache  para cent_os
  package:
   name:
    - httpd
  when: ansible_os_family == "RedHat" #variavel que  busca no setup/factory (checklist da maquina) da maquina
